version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - treasure-hunt-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql;Database=TreasureHuntDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - sql
    networks:
      - treasure-hunt-network
    restart: on-failure:5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - treasure-hunt-network

networks:
  treasure-hunt-network:
    driver: bridge

volumes:
  sqldata: 